-- PostgreSQL schema for the Monster Hunter Wilds dataset.
-- Generated by scripts/schema.py from data/. Do not edit by hand.
--
-- Load order matters: this file creates schemas and tables, then the
-- CSVs in build/<date>/sql/ fill them in dependency order.

CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS monsters;
CREATE SCHEMA IF NOT EXISTS weapons;
CREATE SCHEMA IF NOT EXISTS armor;
CREATE SCHEMA IF NOT EXISTS charms;
CREATE SCHEMA IF NOT EXISTS artian;
CREATE SCHEMA IF NOT EXISTS palico;
CREATE SCHEMA IF NOT EXISTS world;
CREATE SCHEMA IF NOT EXISTS economy;
CREATE SCHEMA IF NOT EXISTS progression;
CREATE SCHEMA IF NOT EXISTS i18n;
CREATE SCHEMA IF NOT EXISTS views;

-- Localisation. One row per GUID and language, which is why entities
-- carry a GUID rather than a column per language.
CREATE TABLE i18n.entries (
  guid   text NOT NULL,
  entry  text,
  source text NOT NULL
);

CREATE TABLE i18n.translations (
  guid text NOT NULL,
  lang text NOT NULL,
  text text NOT NULL
);

-- Consultation grids from the workbook. Not relations: the cell
-- position carries the meaning, so they stay as documents.
CREATE TABLE views.sheets (
  name    text NOT NULL,
  columns jsonb NOT NULL,
  rows    jsonb NOT NULL
);

-- armor/armor.json
CREATE TABLE armor.armor (
  row_id bigint NOT NULL,
  index_ bigint,
  series text,
  part text,
  name text,
  description text,
  defense bigint,
  res_fire bigint,
  res_water bigint,
  res_thunder bigint,
  res_ice bigint,
  res_dragon bigint,
  slots text,
  name_guid text,
  description_guid text,
  source_row integer
);
CREATE TABLE armor.armor_skills (
  armor_row_id bigint NOT NULL,
  position integer NOT NULL,
  value text
);
CREATE TABLE armor.armor_skill_levels (
  armor_row_id bigint NOT NULL,
  position integer NOT NULL,
  value text
);

-- armor/layered.json
CREATE TABLE armor.layered (
  row_id bigint NOT NULL,
  index_ bigint,
  data_value bigint,
  series text,
  part text,
  name_male text,
  name_female text,
  name_male_guid text,
  name_female_guid text,
  source_row integer
);

-- armor/recipes.json
CREATE TABLE armor.recipes (
  row_id bigint NOT NULL,
  index_ bigint,
  recipe_id text,
  series text,
  part text,
  key_item text,
  key_monster text,
  key_story text,
  hunter_rank bigint,
  source_row integer
);
CREATE TABLE armor.recipes_materials (
  recipes_row_id bigint NOT NULL,
  position integer NOT NULL,
  item_id text,
  item_name text,
  quantity bigint
);

-- armor/recommendations.json
CREATE TABLE armor.recommendations (
  row_id bigint NOT NULL,
  index_ bigint,
  data_id bigint,
  sort_id bigint,
  story_flag text,
  series text,
  part text,
  source_row integer
);

-- armor/series.json
CREATE TABLE armor.series (
  row_id bigint NOT NULL,
  index_ bigint,
  series text,
  name text,
  rarity bigint,
  price bigint,
  type_ text,
  sort_id bigint,
  full_set boolean,
  name_guid text,
  source_row integer
);

-- armor/sp_upgrade_costs.json
CREATE TABLE armor.sp_upgrade_costs (
  row_id bigint NOT NULL,
  index_ bigint,
  rarity bigint,
  cost text,
  source_row integer
);

-- armor/upgrade_recipes.json
CREATE TABLE armor.upgrade_recipes (
  row_id bigint NOT NULL,
  index_ bigint,
  series text,
  source_row integer
);
CREATE TABLE armor.upgrade_recipes_materials (
  upgrade_recipes_row_id bigint NOT NULL,
  position integer NOT NULL,
  item_id text,
  item_name text,
  quantity text
);

-- armor/upgrades.json
CREATE TABLE armor.upgrades (
  row_id bigint NOT NULL,
  index_ bigint,
  rarity bigint,
  mission_id text,
  max_level bigint,
  defense_increase text,
  points text,
  price text,
  can_sp_upgrade boolean,
  source_row integer
);

-- artian/bonus_categories.json
CREATE TABLE artian.bonus_categories (
  row_id bigint NOT NULL,
  index_ bigint,
  category_id text,
  probability double precision,
  grinding_max bigint,
  source_row integer
);

-- artian/focus_types.json
CREATE TABLE artian.focus_types (
  row_id bigint NOT NULL,
  index_ bigint,
  focus_type_id text,
  focus_type text,
  icon_color text,
  source_row integer
);

-- artian/parts.json
CREATE TABLE artian.parts (
  row_id bigint NOT NULL,
  index_ bigint,
  fixed_id text,
  part_type text,
  name text,
  sort_id bigint,
  sell_price bigint,
  used_for text,
  name_guid text,
  source_row integer
);

-- artian/skill_groups.json
CREATE TABLE artian.skill_groups (
  row_id bigint NOT NULL,
  index_ bigint,
  data_id bigint,
  series_skill_id text,
  series_skill_name text,
  group_skill_id text,
  group_skill_name text,
  source_row integer
);

-- charms/decorations.json
CREATE TABLE charms.decorations (
  row_id bigint NOT NULL,
  index_ bigint,
  fixed_id text,
  enum text,
  name text,
  description text,
  type_ text,
  rarity bigint,
  price bigint,
  level_ bigint,
  colour text,
  skill_1_level bigint,
  skill_2_level bigint,
  name_guid text,
  description_guid text,
  source_row integer
);

-- charms/pendants.json
CREATE TABLE charms.pendants (
  row_id bigint NOT NULL,
  index_ bigint,
  name text,
  sort_id bigint,
  model_id text,
  story_flag text,
  name_guid text,
  source_row integer
);

-- charms/rng_talisman_skills.json
CREATE TABLE charms.rng_talisman_skills (
  row_id bigint NOT NULL,
  index_ bigint,
  skill_lot text,
  skill_key text,
  skill_id text,
  skill_name text,
  skill_level bigint,
  group_ text,
  talismans_with_group bigint,
  skills_in_group bigint,
  chance double precision,
  source_row integer
);

-- charms/rng_talismans.json
CREATE TABLE charms.rng_talismans (
  row_id bigint NOT NULL,
  index_ bigint,
  amulet text,
  rarity bigint,
  configurations bigint,
  skill_1_group text,
  skill_2_group text,
  skill_3_group text,
  slots_preset text,
  source_row integer
);

-- charms/talisman_recipes.json
CREATE TABLE charms.talisman_recipes (
  row_id bigint NOT NULL,
  index_ bigint,
  data_id bigint,
  type_ text,
  level_ bigint,
  name text,
  key_item_data_id bigint,
  key_monster text,
  key_story text,
  source_row integer
);
CREATE TABLE charms.talisman_recipes_materials (
  talisman_recipes_row_id bigint NOT NULL,
  position integer NOT NULL,
  item_data_id bigint,
  item_id text,
  item_name text,
  quantity bigint
);

-- charms/talismans.json
CREATE TABLE charms.talismans (
  row_id bigint NOT NULL,
  index_ bigint,
  data_id text,
  level_ bigint,
  type_ text,
  name text,
  description text,
  rarity bigint,
  price bigint,
  is_rng boolean,
  name_guid text,
  description_guid text,
  source_row integer
);
CREATE TABLE charms.talismans_skills (
  talismans_row_id bigint NOT NULL,
  position integer NOT NULL,
  skill_id text,
  skill_name text,
  level_ bigint
);

-- core/colours.json
CREATE TABLE core.colours (
  row_id bigint NOT NULL,
  index_ bigint,
  id text,
  name text,
  colour_1 text,
  colour_2 text,
  colour_3 text,
  colour_4 text,
  alpha text,
  source_row integer
);

-- core/hunter_ranks.json
CREATE TABLE core.hunter_ranks (
  row_id bigint NOT NULL,
  index_ bigint,
  rank bigint,
  points bigint,
  cap text,
  source_row integer
);

-- core/items.json
CREATE TABLE core.items (
  row_id bigint NOT NULL,
  data_id bigint,
  index_ bigint,
  item_id text,
  name text,
  description text,
  type_ text,
  rarity bigint,
  max_count bigint,
  palico_max_count bigint,
  sell_price bigint,
  buy_price bigint,
  sort_id bigint,
  consumable boolean,
  healing boolean,
  battle boolean,
  infinite boolean,
  for_money boolean,
  name_guid text,
  description_guid text,
  source_row integer
);

-- core/locales.json
CREATE TABLE core.locales (
  row_id bigint NOT NULL,
  fixed_id text,
  st_id text,
  name text,
  source_row integer
);

-- core/sharpness.json
CREATE TABLE core.sharpness (
  row_id bigint NOT NULL,
  colour text,
  raw_multiplier double precision,
  element_multiplier double precision,
  source_row integer
);

-- core/skill_levels.json
CREATE TABLE core.skill_levels (
  row_id bigint NOT NULL,
  index_ bigint,
  data_id text,
  skill_id text,
  level_ bigint,
  name text,
  description text,
  values_ text,
  unlocks text,
  name_guid text,
  description_guid text,
  source_row integer
);

-- core/skills.json
CREATE TABLE core.skills (
  row_id bigint NOT NULL,
  index_ bigint,
  engine_key text,
  skill_id text,
  type_ text,
  category text,
  name text,
  description text,
  sort_id bigint,
  name_guid text,
  description_guid text,
  source_row integer
);

-- core/species.json
CREATE TABLE core.species (
  row_id bigint NOT NULL,
  index_ bigint,
  code text,
  name text,
  name_guid text,
  source_row integer
);

-- core/weapon_attributes.json
CREATE TABLE core.weapon_attributes (
  row_id bigint NOT NULL,
  index_ bigint,
  id text,
  source_row integer
);

-- core/weapon_types.json
CREATE TABLE core.weapon_types (
  row_id bigint NOT NULL,
  index_ bigint,
  sort_id bigint,
  internal_name text,
  name text,
  multiplier double precision,
  source_row integer
);

-- economy/auto_use_items.json
CREATE TABLE economy.auto_use_items (
  row_id bigint NOT NULL,
  kind text,
  trigger text,
  item_id text,
  item_name text,
  source_row integer
);

-- economy/exchange.json
CREATE TABLE economy.exchange (
  row_id bigint NOT NULL,
  index_ bigint,
  data_id bigint,
  pay_item_id text,
  pay_item_name text,
  pay_quantity bigint,
  reward_item_id text,
  reward_item_name text,
  reward_quantity bigint,
  source_row integer
);

-- economy/fixed_items.json
CREATE TABLE economy.fixed_items (
  row_id bigint NOT NULL,
  index_ bigint,
  item_id text,
  item_name text,
  story_flag text,
  source_row integer
);

-- economy/ingredients.json
CREATE TABLE economy.ingredients (
  row_id bigint NOT NULL,
  index_ bigint,
  item_data_id bigint,
  item_id text,
  item_name text,
  duration bigint,
  health bigint,
  stamina bigint,
  attack bigint,
  defense bigint,
  attribute_resistance bigint,
  meal_skill_key text,
  random_table_1 text,
  random_table_2 text,
  is_main boolean,
  source_row integer
);

-- economy/item_recipes.json
CREATE TABLE economy.item_recipes (
  row_id bigint NOT NULL,
  index_ bigint,
  recipe_id text,
  result_item_id text,
  result_item_name text,
  result_quantity bigint,
  auto_craft boolean,
  source_row integer
);
CREATE TABLE economy.item_recipes_materials (
  item_recipes_row_id bigint NOT NULL,
  position integer NOT NULL,
  item_id text,
  item_name text
);

-- economy/npc_trades.json
CREATE TABLE economy.npc_trades (
  row_id bigint NOT NULL,
  index_ bigint,
  data_id bigint,
  npc text,
  locale text,
  season text,
  max_count bigint,
  special boolean,
  requested_item_data_id bigint,
  requested_item_id text,
  requested_item_name text,
  requested_quantity bigint,
  source_row integer
);
CREATE TABLE economy.npc_trades_rewards (
  npc_trades_row_id bigint NOT NULL,
  position integer NOT NULL,
  item_data_id bigint,
  item_id text,
  item_name text,
  quantity bigint,
  bonus bigint
);

-- economy/shop.json
CREATE TABLE economy.shop (
  row_id bigint NOT NULL,
  index_ bigint,
  item_id text,
  item_name text,
  story_flag text,
  on_sale boolean,
  source_row integer
);

-- economy/slinger_ammo.json
CREATE TABLE economy.slinger_ammo (
  row_id bigint NOT NULL,
  enum_name text,
  enum_value bigint,
  fixed_id text,
  item_data_id bigint,
  item_id text,
  item_name text,
  source_row integer
);

-- economy/support_ship.json
CREATE TABLE economy.support_ship (
  row_id bigint NOT NULL,
  index_ bigint,
  data_id bigint,
  category text,
  item_id text,
  item_name text,
  weapon_type text,
  stock bigint,
  points bigint,
  rate bigint,
  story_flag text,
  source_row integer
);

-- monsters/aggro.json
CREATE TABLE monsters.aggro (
  row_id bigint NOT NULL,
  instance_guid text,
  first_monster text,
  second_monster text,
  combat_disabled boolean,
  attack_hit_type text,
  interpretation text,
  source_row integer
);

-- monsters/ailment_resistances.json
CREATE TABLE monsters.ailment_resistances (
  row_id bigint NOT NULL,
  em_id text,
  monster text,
  resistances_paralysis text,
  resistances_poison text,
  resistances_sleep text,
  resistances_ko text,
  resistances_ride text,
  resistances_parry text,
  resistances_flash text,
  resistances_sonic text,
  resistances_sand_trap text,
  resistances_block text,
  resistances_blast text,
  resistances_exhaust text,
  resistances_pitfall_trap text,
  resistances_shock_trap text,
  resistances_ivy_trap text,
  resistances_capture text,
  resistances_lure_pod text,
  source_row integer
);

-- monsters/appearances.json
CREATE TABLE monsters.appearances (
  row_id bigint NOT NULL,
  locale text,
  monster_count bigint,
  monsters text,
  source_row integer
);

-- monsters/crown_chances.json
CREATE TABLE monsters.crown_chances (
  row_id bigint NOT NULL,
  em_id text,
  monster text,
  rank text,
  mini_size double precision,
  mini_chance double precision,
  large_size double precision,
  large_chance double precision,
  king_size double precision,
  king_chance double precision,
  source_row integer
);

-- monsters/drops.json
CREATE TABLE monsters.drops (
  row_id bigint NOT NULL,
  em_id text,
  monster text,
  reward_type text,
  reward_type_id text,
  parts_index bigint,
  rank text,
  item_data_id bigint,
  item_id text,
  item_name text,
  quantity bigint,
  probability double precision,
  source_row integer
);

-- monsters/hitzones.json
CREATE TABLE monsters.hitzones (
  row_id bigint NOT NULL,
  em_id text,
  monster text,
  instance_guid text,
  slash bigint,
  blow bigint,
  shot bigint,
  fire bigint,
  water bigint,
  thunder bigint,
  ice bigint,
  dragon bigint,
  stun bigint,
  flash bigint,
  source_row integer
);

-- monsters/monsters.json
CREATE TABLE monsters.monsters (
  row_id bigint NOT NULL,
  em_id text,
  enum_value bigint,
  fixed_id text,
  name text,
  class_ text,
  species text,
  base_health bigint,
  base_size double precision,
  crown_small double precision,
  crown_big double precision,
  crown_king double precision,
  points bigint,
  reward bigint,
  frenzied boolean,
  tempered boolean,
  arch_tempered boolean,
  detailed boolean,
  name_guid text,
  description_guid text,
  boss_name_guid text,
  frenzy_name_guid text,
  tempered_name_guid text,
  arch_tempered_name_guid text,
  features_guid text,
  tips_guid text,
  first_capture_guid text,
  memo_guid text,
  icon_large text,
  icon_small text,
  icon_map text,
  icon_endemic text,
  source_row integer
);
CREATE TABLE monsters.monsters_variants (
  monsters_row_id bigint NOT NULL,
  position integer NOT NULL,
  value text
);
CREATE TABLE monsters.monsters_locales (
  monsters_row_id bigint NOT NULL,
  position integer NOT NULL,
  value text
);
CREATE TABLE monsters.monsters_weakness (
  monsters_row_id bigint NOT NULL,
  position integer NOT NULL,
  value text
);
CREATE TABLE monsters.monsters_special_attacks (
  monsters_row_id bigint NOT NULL,
  position integer NOT NULL,
  value text
);

-- monsters/multi_parts.json
CREATE TABLE monsters.multi_parts (
  row_id bigint NOT NULL,
  em_id text,
  monster text,
  instance_guid text,
  vital bigint,
  default_enable text,
  max_count bigint,
  action_ text,
  attribute text,
  link_parts_guid text,
  source_row integer
);

-- monsters/part_breaks.json
CREATE TABLE monsters.part_breaks (
  row_id bigint NOT NULL,
  em_id text,
  monster text,
  instance_guid text,
  target_category text,
  execute_count bigint,
  max_count bigint,
  condition_ text,
  condition_count bigint,
  part_type text,
  source_row integer
);

-- monsters/part_params.json
CREATE TABLE monsters.part_params (
  row_id bigint NOT NULL,
  em_id text,
  monster text,
  scar_standard_size double precision,
  reaction_per double precision,
  base_health bigint,
  scar_pitfall_threshold double precision,
  legendary_scar_pitfall_threshold double precision,
  source_row integer
);

-- monsters/part_types.json
CREATE TABLE monsters.part_types (
  row_id bigint NOT NULL,
  index_ bigint,
  fixed_id text,
  name text,
  rotten_name text,
  description text,
  icon_type text,
  name_guid text,
  rotten_name_guid text,
  description_guid text,
  source_row integer
);

-- monsters/parts.json
CREATE TABLE monsters.parts (
  row_id bigint NOT NULL,
  em_id text,
  monster text,
  instance_guid text,
  part_type text,
  vital bigint,
  kinsect_extract text,
  meat_guid_normal text,
  meat_guid_break text,
  source_row integer
);

-- monsters/quest_rewards.json
CREATE TABLE monsters.quest_rewards (
  row_id bigint NOT NULL,
  em_id text,
  monster text,
  palico_xp bigint,
  source_row integer
);
CREATE TABLE monsters.quest_rewards_guild_points (
  quest_rewards_row_id bigint NOT NULL,
  position integer NOT NULL,
  value bigint
);
CREATE TABLE monsters.quest_rewards_hr_points (
  quest_rewards_row_id bigint NOT NULL,
  position integer NOT NULL,
  value bigint
);
CREATE TABLE monsters.quest_rewards_zenny (
  quest_rewards_row_id bigint NOT NULL,
  position integer NOT NULL,
  value bigint
);

-- monsters/scar_points.json
CREATE TABLE monsters.scar_points (
  row_id bigint NOT NULL,
  em_id text,
  monster text,
  instance_guid text,
  normal_vital bigint,
  tear_vital bigint,
  raw_scar_vital bigint,
  meat_guid text,
  link_parts_guid text,
  size_rate double precision,
  count bigint,
  source_row integer
);

-- monsters/special_attack_types.json
CREATE TABLE monsters.special_attack_types (
  row_id bigint NOT NULL,
  index_ bigint,
  type_ text,
  name text,
  description text,
  source_row integer
);

-- monsters/special_attacks.json
CREATE TABLE monsters.special_attacks (
  row_id bigint NOT NULL,
  index_ bigint,
  id text,
  name text,
  description text,
  source_row integer
);

-- monsters/turf_wars.json
CREATE TABLE monsters.turf_wars (
  row_id bigint NOT NULL,
  attacker text,
  attacker_em_id text,
  receiver text,
  receiver_em_id text,
  attacker_damage_pct double precision,
  receiver_damage_pct double precision,
  type_ text,
  source_row integer
);

-- monsters/weak_points.json
CREATE TABLE monsters.weak_points (
  row_id bigint NOT NULL,
  em_id text,
  monster text,
  instance_guid text,
  vital bigint,
  meat_guid text,
  link_parts_guid text,
  highlight_type text,
  source_row integer
);

-- palico/armor.json
CREATE TABLE palico.armor (
  row_id bigint NOT NULL,
  index_ bigint,
  data_id bigint,
  series text,
  part text,
  name text,
  description text,
  defense bigint,
  res_fire bigint,
  res_water bigint,
  res_thunder bigint,
  res_ice bigint,
  res_dragon bigint,
  name_guid text,
  description_guid text,
  source_row integer
);

-- palico/layered_armor.json
CREATE TABLE palico.layered_armor (
  row_id bigint NOT NULL,
  index_ bigint,
  data_value bigint,
  series text,
  part text,
  name text,
  name_guid text,
  source_row integer
);

-- palico/recipes.json
CREATE TABLE palico.recipes (
  row_id bigint NOT NULL,
  index_ bigint,
  data_id bigint,
  series text,
  category text,
  key_monster text,
  key_story text,
  source_row integer
);
CREATE TABLE palico.recipes_materials (
  recipes_row_id bigint NOT NULL,
  position integer NOT NULL,
  item_data_id bigint,
  item_id text,
  item_name text,
  quantity bigint
);

-- palico/series.json
CREATE TABLE palico.series (
  row_id bigint NOT NULL,
  index_ bigint,
  fixed_id text,
  name text,
  rarity bigint,
  price bigint,
  sort_id bigint,
  full_set boolean,
  rejected boolean,
  name_guid text,
  source_row integer
);

-- palico/weapons.json
CREATE TABLE palico.weapons (
  row_id bigint NOT NULL,
  index_ bigint,
  series text,
  name text,
  description text,
  type_ text,
  element text,
  element_value bigint,
  melee_attack bigint,
  ranged_attack bigint,
  defense_bonus bigint,
  affinity bigint,
  name_guid text,
  description_guid text,
  source_row integer
);

-- progression/dlc.json
CREATE TABLE progression.dlc (
  row_id bigint NOT NULL,
  index_ bigint,
  fixed_id text,
  name text,
  store_category text,
  label text,
  sort_id bigint,
  product_pack text,
  name_guid text,
  source_row integer
);

-- progression/highlights.json
CREATE TABLE progression.highlights (
  row_id bigint NOT NULL,
  index_ bigint,
  id text,
  name text,
  description text,
  unit text,
  weight bigint,
  threshold bigint,
  name_guid text,
  description_guid text,
  source_row integer
);

-- progression/hunt_order.json
CREATE TABLE progression.hunt_order (
  row_id bigint NOT NULL,
  order_ bigint,
  monster text,
  role text,
  min_hr bigint,
  source_row integer
);

-- progression/mantles.json
CREATE TABLE progression.mantles (
  row_id bigint NOT NULL,
  index_ bigint,
  skill_id text,
  description text,
  story_flag text,
  sort_id bigint,
  item_id text,
  description_guid text,
  source_row integer
);

-- progression/medals.json
CREATE TABLE progression.medals (
  row_id bigint NOT NULL,
  index_ bigint,
  id text,
  name text,
  description text,
  hidden boolean,
  monster text,
  em_id text,
  name_guid text,
  description_guid text,
  source_row integer
);

-- progression/mission_reward_tables.json
CREATE TABLE progression.mission_reward_tables (
  row_id bigint NOT NULL,
  index_ bigint,
  mission_id text,
  mission_name text,
  common_table_id bigint,
  target_table_id bigint,
  quest_table_id bigint,
  source_row integer
);

-- progression/mission_rewards.json
CREATE TABLE progression.mission_rewards (
  row_id bigint NOT NULL,
  index_ bigint,
  data_id bigint,
  table_id bigint,
  lot_type text,
  additional_lot_type text,
  item_data_id bigint,
  item_id text,
  item_name text,
  quantity bigint,
  probability double precision,
  source_row integer
);

-- progression/missions.json
CREATE TABLE progression.missions (
  row_id bigint NOT NULL,
  mission_id text,
  enum_value bigint,
  fixed_id bigint,
  name text,
  source_row integer
);

-- progression/name_plates.json
CREATE TABLE progression.name_plates (
  row_id bigint NOT NULL,
  index_ bigint,
  id text,
  name text,
  description text,
  medal_id text,
  mission_id text,
  name_guid text,
  description_guid text,
  source_row integer
);

-- progression/npcs.json
CREATE TABLE progression.npcs (
  row_id bigint NOT NULL,
  fixed_id text,
  index_ bigint,
  npc_id text,
  name text,
  name_guid text,
  source_row integer
);

-- progression/profile_backgrounds.json
CREATE TABLE progression.profile_backgrounds (
  row_id bigint NOT NULL,
  index_ bigint,
  id text,
  name text,
  description text,
  open_type text,
  mission_id text,
  name_guid text,
  description_guid text,
  source_row integer
);

-- progression/title_conjunctions.json
CREATE TABLE progression.title_conjunctions (
  row_id bigint NOT NULL,
  index_ bigint,
  id text,
  name text,
  open_type text,
  mission_id text,
  name_guid text,
  description_guid text,
  source_row integer
);

-- progression/title_words.json
CREATE TABLE progression.title_words (
  row_id bigint NOT NULL,
  index_ bigint,
  id text,
  name text,
  open_type text,
  mission_id text,
  monster text,
  locale text,
  name_guid text,
  description_guid text,
  source_row integer
);

-- weapons/bow_coatings.json
CREATE TABLE weapons.bow_coatings (
  row_id bigint NOT NULL,
  index_ bigint,
  name text,
  source_row integer
);

-- weapons/bowgun_ammo_types.json
CREATE TABLE weapons.bowgun_ammo_types (
  row_id bigint NOT NULL,
  index_ bigint,
  name text,
  source_row integer
);

-- weapons/bowgun_mod_patterns.json
CREATE TABLE weapons.bowgun_mod_patterns (
  row_id bigint NOT NULL,
  index_ bigint,
  data_id bigint,
  pattern_id text,
  mod_id text,
  mod text,
  is_default boolean,
  source_row integer
);

-- weapons/bowgun_mods.json
CREATE TABLE weapons.bowgun_mods (
  row_id bigint NOT NULL,
  fixed_id text,
  index_ bigint,
  name text,
  description text,
  value_1 bigint,
  value_2 bigint,
  name_guid text,
  description_guid text,
  source_row integer
);

-- weapons/hunting_horn_melodies.json
CREATE TABLE weapons.hunting_horn_melodies (
  row_id bigint NOT NULL,
  melody text,
  notes text,
  source_row integer
);

-- weapons/hunting_horn_notes.json
CREATE TABLE weapons.hunting_horn_notes (
  row_id bigint NOT NULL,
  horn_type text,
  notes text,
  source_row integer
);

-- weapons/kinsect_recipes.json
CREATE TABLE weapons.kinsect_recipes (
  row_id bigint NOT NULL,
  index_ bigint,
  kinsect text,
  upgrades_from text,
  source_row integer
);
CREATE TABLE weapons.kinsect_recipes_materials (
  kinsect_recipes_row_id bigint NOT NULL,
  position integer NOT NULL,
  item_data_id bigint,
  item_id text,
  item_name text,
  quantity bigint
);

-- weapons/kinsects.json
CREATE TABLE weapons.kinsects (
  row_id bigint NOT NULL,
  fixed_id text,
  index_ bigint,
  id text,
  name text,
  rarity bigint,
  price bigint,
  attack_type text,
  powder text,
  skill_type text,
  attack text,
  move_speed text,
  recovery text,
  powder_level text,
  name_guid text,
  source_row integer
);

-- weapons/recipes.json
CREATE TABLE weapons.recipes (
  row_id bigint NOT NULL,
  index_ bigint,
  recipe_number bigint,
  weapon_type text,
  weapon_id bigint,
  weapon_name text,
  upgrades_from text,
  key_monster text,
  key_story text,
  orphan boolean,
  source_row integer
);
CREATE TABLE weapons.recipes_materials (
  recipes_row_id bigint NOT NULL,
  position integer NOT NULL,
  item_data_id bigint,
  item_id text,
  item_name text,
  quantity bigint
);

-- weapons/recommendations.json
CREATE TABLE weapons.recommendations (
  row_id bigint NOT NULL,
  index_ bigint,
  data_id bigint,
  sort_id bigint,
  story_flag text,
  weapon_type text,
  param_id bigint,
  source_row integer
);

-- weapons/series.json
CREATE TABLE weapons.series (
  row_id bigint NOT NULL,
  fixed_id text,
  index_ bigint,
  enum text,
  name text,
  name_guid text,
  source_row integer
);

-- weapons/tree_nodes.json
CREATE TABLE weapons.tree_nodes (
  row_id bigint NOT NULL,
  weapon_type text,
  weapon_id bigint,
  tier bigint,
  row bigint,
  lineage text,
  previous_weapon_id bigint,
  enabled boolean,
  node_guid text,
  source_row integer
);
CREATE TABLE weapons.tree_nodes_next_weapon_ids (
  tree_nodes_row_id bigint NOT NULL,
  position integer NOT NULL,
  value bigint
);

-- weapons/weapons.json
CREATE TABLE weapons.weapons (
  row_id bigint NOT NULL,
  weapon_type text,
  sheet text,
  index_ bigint,
  id bigint,
  name text,
  description text,
  rarity bigint,
  price bigint,
  attack bigint,
  defense bigint,
  affinity bigint,
  element text,
  element_value bigint,
  slots text,
  name_guid text,
  description_guid text,
  sharpness_red bigint,
  sharpness_orange bigint,
  sharpness_yellow bigint,
  sharpness_green bigint,
  sharpness_blue bigint,
  sharpness_white bigint,
  sharpness_purple bigint,
  sharpness_handicraft_red bigint,
  sharpness_handicraft_orange bigint,
  sharpness_handicraft_yellow bigint,
  sharpness_handicraft_green bigint,
  sharpness_handicraft_blue bigint,
  sharpness_handicraft_white bigint,
  sharpness_handicraft_purple bigint,
  source_row integer
);
CREATE TABLE weapons.weapons_skills (
  weapons_row_id bigint NOT NULL,
  position integer NOT NULL,
  skill_id text,
  skill_name text,
  level_ bigint
);

-- world/endemic_life.json
CREATE TABLE world.endemic_life (
  row_id bigint NOT NULL,
  em_id text,
  fixed_id text,
  name text,
  points bigint,
  source_row integer
);
CREATE TABLE world.endemic_life_locales (
  endemic_life_row_id bigint NOT NULL,
  position integer NOT NULL,
  value text
);

-- world/fish.json
CREATE TABLE world.fish (
  row_id bigint NOT NULL,
  em_id text,
  fixed_id text,
  name text,
  is_whopper boolean,
  best_lure text,
  best_lure_action text,
  points bigint,
  base_size double precision,
  min_size double precision,
  max_size double precision,
  source_row integer
);
CREATE TABLE world.fish_locales (
  fish_row_id bigint NOT NULL,
  position integer NOT NULL,
  value text
);

-- world/gimmick_texts.json
CREATE TABLE world.gimmick_texts (
  row_id bigint NOT NULL,
  index_ bigint,
  gimmick_id text,
  name text,
  description text,
  name_guid text,
  description_guid text,
  source_row integer
);

-- world/gimmicks.json
CREATE TABLE world.gimmicks (
  row_id bigint NOT NULL,
  index_ bigint,
  gimmick_id text,
  name text,
  points bigint,
  map_display_type text,
  icon_colour text,
  palico_pick boolean,
  advisor_pick boolean,
  source_row integer
);

-- world/zones.json
CREATE TABLE world.zones (
  row_id bigint NOT NULL,
  area_id text,
  area_number bigint,
  floor bigint,
  subfloor bigint,
  pop_shade text,
  temperature text,
  environment text,
  source_row integer
);

