-- Convenience views over the Monster Hunter Wilds dataset.
-- Generated by scripts/schema.py. Apply after schema/constraints.sql.

-- Every item in every language, one row per language.
CREATE VIEW core.items_localised AS
SELECT i.data_id, i.item_id, i.name AS name_en, t.lang,
       t.text AS name, d.text AS description
FROM core.items i
JOIN i18n.translations t ON t.guid = i.name_guid
LEFT JOIN i18n.translations d
       ON d.guid = i.description_guid AND d.lang = t.lang;

-- Every monster in every language, with its icon file.
CREATE VIEW monsters.monsters_localised AS
SELECT m.em_id, m.name AS name_en, m.class_, m.species, m.base_health,
       m.icon_large, t.lang, t.text AS name, e.text AS description
FROM monsters.monsters m
JOIN i18n.translations t ON t.guid = m.name_guid
LEFT JOIN i18n.translations e
       ON e.guid = m.description_guid AND e.lang = t.lang;

-- Reward tables with the monster and item spelled out.
CREATE VIEW monsters.drops_detailed AS
SELECT d.em_id, m.name AS monster, d.rank, d.reward_type,
       i.item_id, i.name AS item, d.quantity, d.probability
FROM monsters.drops d
JOIN monsters.monsters m ON m.em_id = d.em_id
LEFT JOIN core.items i ON i.data_id = d.item_data_id;

-- Which monsters drop a given item. The reverse lookup an app needs when a
-- player asks where to farm something.
CREATE VIEW monsters.item_sources AS
SELECT i.item_id, i.name AS item, m.name AS monster, d.rank,
       d.reward_type, d.probability
FROM monsters.drops d
JOIN core.items i ON i.data_id = d.item_data_id
JOIN monsters.monsters m ON m.em_id = d.em_id;

-- Weapons with their position in the upgrade tree.
CREATE VIEW weapons.weapons_in_tree AS
SELECT w.weapon_type, w.id, w.name, w.rarity, w.attack, w.affinity,
       w.element, w.element_value, n.lineage, n.tier, n.previous_weapon_id
FROM weapons.weapons w
LEFT JOIN weapons.tree_nodes n
       ON n.weapon_type = w.weapon_type AND n.weapon_id = w.id;

-- The upgrade graph as edges, ready to walk or render.
CREATE VIEW weapons.upgrade_edges AS
SELECT n.weapon_type, n.lineage,
       n.weapon_id AS from_id, w.name AS from_name, n.tier AS from_tier,
       e.value AS to_id, t.name AS to_name
FROM weapons.tree_nodes n
JOIN weapons.tree_nodes_next_weapon_ids e ON e.tree_nodes_row_id = n.row_id
JOIN weapons.weapons w ON w.weapon_type = n.weapon_type AND w.id = n.weapon_id
LEFT JOIN weapons.weapons t ON t.weapon_type = n.weapon_type AND t.id = e.value;

-- Armour pieces with their series.
CREATE VIEW armor.pieces_with_series AS
SELECT a.series, s.name AS series_name, s.rarity, a.part, a.name,
       a.defense, a.res_fire, a.res_water, a.res_thunder, a.res_ice,
       a.res_dragon, a.slots
FROM armor.armor a
JOIN armor.series s ON s.series = a.series;

-- Every craftable thing that needs a given item, across weapons, armour,
-- talismans and Palico gear. The other reverse lookup an app needs.
CREATE VIEW economy.item_demand AS
SELECT 'weapon' AS kind, r.weapon_name AS product, m.item_id, m.item_name,
       m.quantity
FROM weapons.recipes r JOIN weapons.recipes_materials m ON m.recipes_row_id = r.row_id
UNION ALL
SELECT 'armor', a.series || ' ' || a.part, m.item_id, m.item_name, m.quantity
FROM armor.recipes a JOIN armor.recipes_materials m ON m.recipes_row_id = a.row_id
UNION ALL
SELECT 'talisman', t.name, m.item_id, m.item_name, m.quantity
FROM charms.talisman_recipes t
JOIN charms.talisman_recipes_materials m ON m.talisman_recipes_row_id = t.row_id
UNION ALL
SELECT 'palico', p.series || ' ' || p.category, m.item_id, m.item_name, m.quantity
FROM palico.recipes p JOIN palico.recipes_materials m ON m.recipes_row_id = p.row_id;

-- Cardinality assertions.
--
-- Nothing else checks these views: check_output.py validates data/, and the
-- foreign keys validate the tables, but a view is hand-written SQL and a join
-- on the wrong column silently returns fewer rows instead of failing. That is
-- not hypothetical: upgrade_edges once returned 71 rows instead of 957 because
-- it joined a surrogate key against a game id.
--
-- Each expectation below is expressed from a different angle than the view it
-- guards, so a typo in the view cannot satisfy both.

DO $$
DECLARE
  got bigint;
  want bigint;
  problems text := '';
  PROCEDURE_NAME text;
BEGIN
  -- one row per item and language that has a translated name
  SELECT count(*) INTO got FROM core.items_localised;
  SELECT count(*) INTO want FROM core.items i
    JOIN i18n.translations t ON t.guid = i.name_guid;
  IF got <> want THEN
    problems := problems || format('core.items_localised: %s rows, expected %s; ',
                                   got, want);
  END IF;

  SELECT count(*) INTO got FROM monsters.monsters_localised;
  SELECT count(*) INTO want FROM monsters.monsters m
    JOIN i18n.translations t ON t.guid = m.name_guid;
  IF got <> want THEN
    problems := problems || format('monsters.monsters_localised: %s rows, expected %s; ',
                                   got, want);
  END IF;

  -- every drop row survives: the monster key is a enforced foreign key and the
  -- item join is a LEFT JOIN
  SELECT count(*) INTO got FROM monsters.drops_detailed;
  SELECT count(*) INTO want FROM monsters.drops;
  IF got <> want THEN
    problems := problems || format('monsters.drops_detailed: %s rows, expected %s; ',
                                   got, want);
  END IF;

  -- only the drops that name an item
  SELECT count(*) INTO got FROM monsters.item_sources;
  SELECT count(*) INTO want FROM monsters.drops WHERE item_data_id IS NOT NULL;
  IF got <> want THEN
    problems := problems || format('monsters.item_sources: %s rows, expected %s; ',
                                   got, want);
  END IF;

  -- one row per weapon, tree membership is optional
  SELECT count(*) INTO got FROM weapons.weapons_in_tree;
  SELECT count(*) INTO want FROM weapons.weapons;
  IF got <> want THEN
    problems := problems || format('weapons.weapons_in_tree: %s rows, expected %s; ',
                                   got, want);
  END IF;

  -- one edge per declared link
  SELECT count(*) INTO got FROM weapons.upgrade_edges;
  SELECT count(*) INTO want FROM weapons.tree_nodes_next_weapon_ids;
  IF got <> want THEN
    problems := problems || format('weapons.upgrade_edges: %s rows, expected %s; ',
                                   got, want);
  END IF;

  -- every armour piece whose series exists
  SELECT count(*) INTO got FROM armor.pieces_with_series;
  SELECT count(*) INTO want FROM armor.armor a
    WHERE EXISTS (SELECT 1 FROM armor.series s WHERE s.series = a.series);
  IF got <> want THEN
    problems := problems || format('armor.pieces_with_series: %s rows, expected %s; ',
                                   got, want);
  END IF;

  -- the four crafting systems concatenated
  SELECT count(*) INTO got FROM economy.item_demand;
  SELECT (SELECT count(*) FROM weapons.recipes_materials)
       + (SELECT count(*) FROM armor.recipes_materials)
       + (SELECT count(*) FROM charms.talisman_recipes_materials)
       + (SELECT count(*) FROM palico.recipes_materials) INTO want;
  IF got <> want THEN
    problems := problems || format('economy.item_demand: %s rows, expected %s; ',
                                   got, want);
  END IF;

  IF problems <> '' THEN
    RAISE EXCEPTION 'view cardinality check failed: %', problems;
  END IF;
  RAISE NOTICE 'all 8 views return the expected number of rows';
END
$$;
